---
- hosts: all
  become: yes
  tasks:
    - name: Update apt repository and install prerequisites
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Install docker and other packages
      apt:
        name:
          - docker.io
          - jq
          - git
          - ncdu
          - geoip-bin
          - geoip-database
        state: present

    - name: Install Docker Compose
      shell: |
        curl -sL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s | tr 'A-Z' 'a-z')-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create Docker network for services
      docker_network:
        name: my_network

    - name: Deploy services using Docker Compose
      copy:
        dest: /opt/ushurucalc/docker-compose.yml
        content: |
          version: '3.8'
          services:
            backend:
              ports:
                - "127.0.0.1:9090:9091"
              restart: always
              build:
                context: .
                dockerfile: Dockerfile.pypy
              environment:
                - FLASK_SERVER_PORT=9091

    - name: Start Docker Compose services
      shell: docker-compose up -d
      args:
        chdir: /opt/ushurucalc/
